name: Onboard Payment Refund API

on:
  workflow_dispatch:
  push:
    paths:
      - 'specs/payment-refund-api-openapi.yaml'
      - '.github/workflows/onboard-api.yml'

jobs:
  onboard:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: postman-cs/postman-api-onboarding-action@v0
        with:
          project-name: payment-refund-api
          domain: payments
          domain-code: PAY
          requester-email: singhaksshay@icloud.com
          spec-url: https://raw.githubusercontent.com/singhaksshay/postman-payment-refund-api/main/specs/payment-refund-api-openapi.yaml
          environments-json: '["prod","uat","qa","dev"]'
          env-runtime-urls-json: '{"prod":"https://api.payments.example.com/v2","uat":"https://api-uat.payments.example.com/v2","qa":"https://api-qa.payments.example.com/v2","dev":"https://api-dev.payments.example.com/v2"}'
          generate-ci-workflow: false
          postman-api-key: ${{ secrets.POSTMAN_API_KEY }}
          postman-access-token: ${{ secrets.POSTMAN_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-fallback-token: ${{ secrets.GH_FALLBACK_TOKEN }}
